controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 3.0
  min_vel_x: -2.0
  max_vel_y: 2.0
  min_vel_y: -2.0
  max_vel_theta: 10.0
  min_vel_theta: -10.0
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 50
  acc_lim_x: 3
  acc_lim_y: 3

  holonomic_robot: true
  prefer_forward_cost_function: 0.0
  
  #y_vels: '-1,-0.9,-0.8,-0.7,-0.6,-0.5,-0.4,-0.3,-0.2,-0.1,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1' 