controller_frequency: 5

TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_vel_y: 2.0
  min_vel_y: 0.1
  max_vel_theta: 5.0
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 10
  acc_lim_x: 3
  acc_lim_y: 3

  holonomic_robot: true
  
  y_vels: '-1,-0.9,-0.8,-0.7,-0.6,-0.5,-0.4,-0.3,-0.2,-0.1,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1' 