controller_frequency: 10
recovery_behaviour_enabled: false

#DWAPlannerROS:
TrajectoryPlannerROS:
  max_vel_x: 3
  min_vel_x: -3
  max_rotational_vel: 1
  min_rotational_vel: -1
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.1
  escape_vel: -0.1
  acc_lim_x: 3
  acc_lim_y: 2
  acc_lim_theta: 30

  holonomic_robot: true
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
  pdist_scale: 0.8
  gdist_scale: 0.6
  meter_scoring: true
  prefer_forward_cost_function: 0.0

  # forward simulation
  sim_time: 1
  vx_samples: 10
  vy_samples: 10
  vtheta_samples: 10
  sim_granularity: 0.1
  angular_sim_granularity: 0.2
  penalize_negative_x: false

  # weights
  occdist_scale: 10
    
  dwa: true
  simple_attractor: false
  
  
  