<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.027" />
  <xacro:property name="wheel_thickness" value="0.015" />
  <xacro:property name="robot_wheel_radius" value="0.075" />
  
  <xacro:include filename="$(find ssl_robot_description)/urdf/sub_wheel.xacro" />
  
  <xacro:macro name="wheel" params="suffix parent origin_x origin_y rotation">
    
    <link name="wheel_${suffix}">
      <inertial>
        <origin xyz="${wheel_thickness/2} 0 0" rpy="0 1.5707 0" />
        <mass value="0.8000" />
        <inertia ixx="0.012593750" ixy="0" ixz="0" iyy="0.012593750" iyz="0" izz="0.025000000" />
      </inertial>
      
      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 0" />
        <geometry>
          <mesh filename="package://ssl_robot_description/meshes/UBG-Rad.stl"/>
        </geometry>
      </visual>
      
<!--
      <collision>
        <origin xyz="${wheel_thickness/2} 0 0" rpy="0 1.5707 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
-->
    </link>
    
    <joint name="base_wheel_${suffix}" type="continuous">
      <parent link="${parent}" />
      <child link="wheel_${suffix}" />
      <axis xyz="1 0 0" />
      <origin xyz="${robot_wheel_radius*origin_x} ${robot_wheel_radius*origin_y} ${wheel_radius-ground_clearance}" rpy="0 0 ${rotation}" />
      <dynamics damping="0.05" friction="0.0" />
      <!-- (3m/s / 2*pi*r) * 2 * pi -> 3m/s / r-->
      <limit lower="0" upper="0"
             effort="5" velocity="${3/wheel_radius}" />
    </joint>
                  
    <xacro:sub_wheel suffix="${suffix}_1" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*1.000000}" origin_y="${(wheel_radius-0.005)*0.000000}" rotation="0.000000" />
    <xacro:sub_wheel suffix="${suffix}_2" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.951057}" origin_y="${(wheel_radius-0.005)*0.309017}" rotation="0.314159" />
    <xacro:sub_wheel suffix="${suffix}_3" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.809017}" origin_y="${(wheel_radius-0.005)*0.587785}" rotation="0.628319" />
    <xacro:sub_wheel suffix="${suffix}_4" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.587785}" origin_y="${(wheel_radius-0.005)*0.809017}" rotation="0.942478" />
    <xacro:sub_wheel suffix="${suffix}_5" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.309017}" origin_y="${(wheel_radius-0.005)*0.951057}" rotation="1.256637" />
    <xacro:sub_wheel suffix="${suffix}_6" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.000000}" origin_y="${(wheel_radius-0.005)*1.000000}" rotation="1.570796" />
    <xacro:sub_wheel suffix="${suffix}_7" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.309017}" origin_y="${(wheel_radius-0.005)*0.951057}" rotation="1.884956" />
    <xacro:sub_wheel suffix="${suffix}_8" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.587785}" origin_y="${(wheel_radius-0.005)*0.809017}" rotation="2.199115" />
    <xacro:sub_wheel suffix="${suffix}_9" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.809017}" origin_y="${(wheel_radius-0.005)*0.587785}" rotation="2.513274" />
    <xacro:sub_wheel suffix="${suffix}_10" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.951057}" origin_y="${(wheel_radius-0.005)*0.309017}" rotation="2.827433" />
    <xacro:sub_wheel suffix="${suffix}_11" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-1.000000}" origin_y="${(wheel_radius-0.005)*0.000000}" rotation="3.141593" />
    <xacro:sub_wheel suffix="${suffix}_12" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.951057}" origin_y="${(wheel_radius-0.005)*-0.309017}" rotation="3.455752" />
    <xacro:sub_wheel suffix="${suffix}_13" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.809017}" origin_y="${(wheel_radius-0.005)*-0.587785}" rotation="3.769911" />
    <xacro:sub_wheel suffix="${suffix}_14" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.587785}" origin_y="${(wheel_radius-0.005)*-0.809017}" rotation="4.084070" />
    <xacro:sub_wheel suffix="${suffix}_15" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.309017}" origin_y="${(wheel_radius-0.005)*-0.951057}" rotation="4.398230" />
    <xacro:sub_wheel suffix="${suffix}_16" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*-0.000000}" origin_y="${(wheel_radius-0.005)*-1.000000}" rotation="4.712389" />
    <xacro:sub_wheel suffix="${suffix}_17" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.309017}" origin_y="${(wheel_radius-0.005)*-0.951057}" rotation="5.026548" />
    <xacro:sub_wheel suffix="${suffix}_18" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.587785}" origin_y="${(wheel_radius-0.005)*-0.809017}" rotation="5.340708" />
    <xacro:sub_wheel suffix="${suffix}_19" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.809017}" origin_y="${(wheel_radius-0.005)*-0.587785}" rotation="5.654867" />
    <xacro:sub_wheel suffix="${suffix}_20" parent="wheel_${suffix}" origin_x="${(wheel_radius-0.005)*0.951057}" origin_y="${(wheel_radius-0.005)*-0.309017}" rotation="5.969026" />
    
    <transmission name="tran_${suffix}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="base_wheel_${suffix}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="wheel_${suffix}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
