<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.027" />
  <xacro:property name="wheel_thickness" value="0.015" />
  <xacro:property name="robot_wheel_radius" value="0.075" />
  
  <xacro:macro name="wheel" params="suffix parent origin_x origin_y rotation">
    
    <link name="wheel_${suffix}">
      <inertial>
        <origin xyz="0.005 0 0" rpy="0 1.5707 0" />
        <mass value="0.10" />
        <inertia ixx="0.000016" ixy="0" ixz="0" iyy="0.000016" iyz="0" izz="0.000031" />
      </inertial>
      <visual name="wheel-visual" >
        <origin xyz="0 0 0" rpy="0 1.5707 0" />
        <geometry>
          <mesh filename="package://ssl_robot_description/meshes/UBG-Rad.stl"/>
        </geometry>
      </visual>
      <collision name="wheel">
        <origin xyz="0.005 0 0" rpy="0 1.5707 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
      </collision>
    </link>
    
    <link name="motor_${suffix}">
      <inertial>
        <origin xyz="${robot_wheel_radius-wheel_thickness-0.005} 0 ${wheel_radius}" rpy="0 0 0" />
        <mass value="0.10" />
        <inertia ixx="0.000042" ixy="0" ixz="0" iyy="0.000022" iyz="0" izz="0.000022" />
      </inertial>
      <visual>
        <origin xyz="${robot_wheel_radius-wheel_thickness-0.0005} 0 ${wheel_radius}" rpy="0 0 0" />
        <geometry>
          <box size="0.001 ${wheel_radius*2} ${wheel_radius*2}" />
        </geometry>
      </visual>
    </link>
    
    <joint name="base_wheel_${suffix}" type="continuous">
      <parent link="motor_${suffix}" />
      <child link="wheel_${suffix}" />
      <axis xyz="1 0 0" />
      <origin xyz="${robot_wheel_radius} 0 ${wheel_radius-ground_clearance}" rpy="0 0 0" />
    </joint>
              
    <joint name="base_motor_${suffix}" type="revolute">
      <parent link="${parent}" />
      <child link="motor_${suffix}" />
      <axis xyz="0 0 1" />
      <limit effort="30" velocity="1.0" lower="${rotation}" upper="${rotation}" />
      <origin xyz="0 0 0" 
              rpy="0 0 0" />
    </joint>
    
    <transmission name="tran_${suffix}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="base_wheel_${suffix}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="wheel_${suffix}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
